### ISSUE TITLE
isOpen() returns false

### ISSUE THREAD

**Issue by surya557** [dexie/dexie-website-old#67]
Hello,

isOpen() returns false when I redirect from a different url. I'm using SSO login, so after successful login and navigating back to  my application, it returns false. Could you please let me know when isOpen() returns false?

**Comment by dfahlander** [comment]
The Dexie instance will never be in an open state when page is loading. This method is normally not needed to be used by applications if you have opened your Dexie instance in the [default mode (auto-open)](https://dexie.org/docs/Dexie/Dexie#options) you just start using the db right away.

Do you need to call db.isOpen() at all or there another way?

**Comment by surya557** [comment]
Thank you! That information helps a lot. I'm actually using isOpen to check if the DB is not closed and have no issues with writing to DB, because sometimes, I get an error saying DB connection is closed.

**Comment by dfahlander** [comment]
I see. The reason for it to become suddenly closed can only be that you open a newer version of your db in another tab - then the old version of the app will close itself in order to let the new version proceed with the upgrade. You can ovverride this behavior using the [versionchange event](https://dexie.org/docs/Dexie/Dexie.on.versionchange).

**Comment by surya557** [comment]
Awesome, I'll look into that. Thank you so much for your help!
